[article]
  showDate = true
  showTableOfContents = true
  tocOpen = true
  showViews = false
  showLikes = false
  showDateOnlyInArticle = false
  showDateUpdated = true
  showAuthor = false
  showAuthorBottom = false
  showHero = false
  layoutBackgroundBlur = true
  layoutBackgroundHeaderSpace = true
  showBreadcrumbs = true
  showDraftLabel = true
  showEdit = false
  editAppendPath = true
  seriesOpened = false
  showHeadingAnchors = true
  showPagination = true
  invertPagination = false
  showReadingTime = true
  # （這裡本來有一個 showTableOfContents = false，記得刪掉！）
  showTaxonomies = false
  showCategoryOnly = false
  showAuthorsBadges = false
  showWordCount = false
  showZenMode = false